CREATE TABLE TBL_BRANDS (
     ID BIGINT PRIMARY KEY,
     NAME VARCHAR(255) NOT NULL,

     CONSTRAINT PK_TBL_BRANDS PRIMARY KEY (ID)
);

CREATE TABLE TBL_PRICE_LISTS (
     ID BIGINT PRIMARY KEY,
     NAME VARCHAR(255) NOT NULL,

     CONSTRAINT PK_TBL_PRICE_LISTS PRIMARY KEY (ID)
);

CREATE TABLE TBL_PRODUCTS (
     ID BIGINT PRIMARY KEY,

     CONSTRAINT PK_TBL_PRODUCTS PRIMARY KEY (ID)
);

CREATE TABLE TBL_PRICES (
    ID UUID NOT NULL,
    BRAND_ID BIGINT NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRICE_LIST_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    PRIORITY INTEGER NOT NULL,
    PRICE NUMERIC(15, 2) NOT NULL,
    CURR VARCHAR(3) NOT NULL,

    CONSTRAINT PK_TBL_PRICES PRIMARY KEY (ID)
);

ALTER TABLE TBL_PRICES ADD CONSTRAINT FK_TBL_PRICES_ON_BRAND_ID
FOREIGN KEY (BRAND_ID) REFERENCES TBL_BRANDS (id);

ALTER TABLE TBL_PRICES ADD CONSTRAINT FK_TBL_PRICES_ON_PRICE_LIST_ID
FOREIGN KEY (PRICE_LIST_ID) REFERENCES TBL_PRICE_LISTS (id);

ALTER TABLE TBL_PRICES ADD CONSTRAINT FK_TBL_PRICES_ON_PRODUCT_ID
FOREIGN KEY (PRODUCT_ID) REFERENCES TBL_PRODUCTS (id);

CREATE INDEX IDX_TBL_PRICES_ON_BRAND_ID_PRODUCT_ID_START_DATE_END_DATE
ON TBL_PRICES(BRAND_ID, PRODUCT_ID, START_DATE, END_DATE, PRIORITY DESC);
