server:
  port: 8080

spring:
  application.name: price-service
  mandatoryFileEncoding: UTF-8
  output.ansi.enabled: always
  main:
    banner-mode: console
    allow-bean-definition-overriding: true
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:mem:price-service
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
    hikari:
      idle-timeout: 10000
      minimum-idle: 2
      maximum-pool-size: 10
      max-lifetime: 30000
  jpa:
    properties.jakarta.persistence.lock:.timeout: 25000
    hibernate.ddl-auto: validate
    show-sql: true
    generate-ddl: false
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    locations: classpath:sql/migration
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
