name: Create branch from issue

on:
  issues:
    types: [opened]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create branch from issue
        id: create_branch
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          ISSUE_TITLE=${{ github.event.issue.title }}
          BRANCH_NAME="issue-${ISSUE_NUMBER}-$(echo "$ISSUE_TITLE" | tr ' ' '-' | tr -cd '[:alnum:]-' | tr '[:upper:]' '[:lower:]')"

          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

          git config user.name github-actions
          git config user.email github-actions@github.com

          git fetch origin
          git checkout -b "$BRANCH_NAME" origin/main
          git push origin "$BRANCH_NAME"

      - name: Comment on issue
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "🔀 A branch \`${{ env.BRANCH_NAME }}\` has been created for this issue."

      - name: Create draft pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}
          base: main
          title: "Fixes #${{ github.event.issue.number }} - ${{ github.event.issue.title }}"
          body: |
            This PR addresses issue #${{ github.event.issue.number }}.

            Fixes #${{ github.event.issue.number }}
          draft: true
